// src/categories.js

export const categories = [
  "Beginner",
  "Cuisine",
  "Health",
  "Dessert",
  "Tips",
  "Snacks",
  "Vegetarian",
  "Vegan",
  "Breakfast",
  "Lunch",
  "Dinner",
  "Gluten-Free",
  "Keto",
  "International",
  "Nepali",
  "Quick Meals",
  "Meal Prep",
  "Festive",
  "Street Food",
  "Baking",
  "Low Carb",
  "High Protein",
  "Seafood",
  "Soups & Stews",
  "Pasta & Noodles",
  "Drinks & Beverages",
  "Comfort Food",
  "Family Friendly",
  "Budget-Friendly",
  "Food Culture",
  "Fusion",
  "Sides & Appetizers",
  "Grilling & BBQ",
  "Spicy",
  "Cooking Techniques",
  "Dietary Restrictions",
];
